export type Product = {
	id: string;
	name: string;
	description: string;
	price: number;
	images: {
		id: string;
		url: string;
		alt: string;
		isMain: boolean;
	}[];
	stock: number;
	categoryId: string;
	category: {
		id: string;
		name: string;
		slug: string;
	};
	rating: {
		rate: number;
		count: number;
	};
};

export const categories = [
	{
		id: 'cat-1',
		name: 'Electrónicos',
		slug: 'electronicos',
		description: 'Productos electrónicos y gadgets de última generación',
	},
	{
		id: 'cat-2',
		name: 'Ropa',
		slug: 'ropa',
		description: 'Ropa y accesorios de moda para todas las edades',
	},
	{
		id: 'cat-3',
		name: 'Hogar',
		slug: 'hogar',
		description: 'Artículos para el hogar y decoración',
	},
	{
		id: 'cat-4',
		name: 'Joyería',
		slug: 'joyeria',
		description: 'Joyería fina y accesorios elegantes',
	},
	{
		id: 'cat-5',
		name: 'Deportes',
		slug: 'deportes',
		description: 'Equipamiento y ropa deportiva',
	},
	{
		id: 'cat-6',
		name: 'Libros',
		slug: 'libros',
		description: 'Libros, ebooks y material educativo',
	},
	{
		id: 'cat-7',
		name: 'Belleza',
		slug: 'belleza',
		description: 'Productos de belleza y cuidado personal',
	},
	{
		id: 'cat-8',
		name: 'Juguetes',
		slug: 'juguetes',
		description: 'Juguetes y juegos para todas las edades',
	},
];

// Productos por categoría
const electronicos: Product[] = [
	{
		id: 'prod-e1',
		name: 'iPhone 14 Pro',
		description: 'El último iPhone con cámara de 48MP y Dynamic Island',
		price: 999.99,
		images: [
			{
				id: 'img-e1-1',
				url: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
				alt: 'iPhone 14 Pro',
				isMain: true,
			},
		],
		stock: 50,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.8, count: 120 },
	},
	{
		id: 'prod-e2',
		name: 'Samsung Galaxy S23',
		description: 'Potencia y elegancia en un smartphone Android',
		price: 899.99,
		images: [
			{
				id: 'img-e2-1',
				url: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
				alt: 'Samsung Galaxy S23',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.7, count: 95 },
	},
	{
		id: 'prod-e3',
		name: 'MacBook Pro M2',
		description: 'Potente laptop para profesionales',
		price: 1299.99,
		images: [
			{
				id: 'img-e3-1',
				url: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg',
				alt: 'MacBook Pro M2',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.9, count: 110 },
	},
	{
		id: 'prod-e4',
		name: 'iPad Air',
		description: 'Tablet versátil con chip M1',
		price: 599.99,
		images: [
			{
				id: 'img-e4-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'iPad Air',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.8, count: 85 },
	},
	{
		id: 'prod-e5',
		name: 'Sony WH-1000XM4',
		description: 'Audífonos inalámbricos con cancelación de ruido',
		price: 349.99,
		images: [
			{
				id: 'img-e5-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Sony WH-1000XM4',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.9, count: 150 },
	},
	{
		id: 'prod-e6',
		name: 'Dell XPS 13',
		description: 'Laptop ultraportátil con pantalla InfinityEdge',
		price: 1199.99,
		images: [
			{
				id: 'img-e6-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Dell XPS 13',
				isMain: true,
			},
		],
		stock: 20,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.7, count: 88 },
	},
	{
		id: 'prod-e7',
		name: 'Nintendo Switch OLED',
		description: 'Consola portátil con pantalla OLED mejorada',
		price: 349.99,
		images: [
			{
				id: 'img-e7-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Nintendo Switch OLED',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.8, count: 200 },
	},
	{
		id: 'prod-e8',
		name: 'Samsung 4K Smart TV',
		description: 'Smart TV 55" con resolución 4K y HDR',
		price: 799.99,
		images: [
			{
				id: 'img-e8-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Samsung 4K Smart TV',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.6, count: 75 },
	},
	{
		id: 'prod-e9',
		name: 'GoPro Hero 11',
		description: 'Cámara de acción 5.3K con estabilización',
		price: 499.99,
		images: [
			{
				id: 'img-e9-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'GoPro Hero 11',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.7, count: 92 },
	},
	{
		id: 'prod-e10',
		name: 'Apple Watch Series 8',
		description: 'Reloj inteligente con monitoreo de salud avanzado',
		price: 399.99,
		images: [
			{
				id: 'img-e10-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Apple Watch Series 8',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.8, count: 130 },
	},
	{
		id: 'prod-e11',
		name: 'DJI Mini 3 Pro',
		description: 'Drone compacto con cámara 4K',
		price: 699.99,
		images: [
			{
				id: 'img-e11-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'DJI Mini 3 Pro',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.9, count: 68 },
	},
	{
		id: 'prod-e12',
		name: 'Amazon Echo Dot',
		description: 'Altavoz inteligente con Alexa',
		price: 49.99,
		images: [
			{
				id: 'img-e12-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Amazon Echo Dot',
				isMain: true,
			},
		],
		stock: 100,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.5, count: 250 },
	},
	{
		id: 'prod-e13',
		name: 'Sony PlayStation 5',
		description: 'Consola de nueva generación con SSD ultrarrápido',
		price: 499.99,
		images: [
			{
				id: 'img-e13-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'PlayStation 5',
				isMain: true,
			},
		],
		stock: 10,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.9, count: 180 },
	},
	{
		id: 'prod-e14',
		name: 'Microsoft Surface Pro 9',
		description: 'Tablet convertible con Windows 11 Pro',
		price: 999.99,
		images: [
			{
				id: 'img-e14-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Microsoft Surface Pro 9',
				isMain: true,
			},
		],
		stock: 20,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.7, count: 95 },
	},
	{
		id: 'prod-e15',
		name: 'Google Pixel 7 Pro',
		description: 'Smartphone con la mejor cámara del mercado',
		price: 899.99,
		images: [
			{
				id: 'img-e15-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Google Pixel 7 Pro',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.8, count: 110 },
	},
	{
		id: 'prod-e16',
		name: 'Bose QuietComfort 45',
		description: 'Audífonos con cancelación de ruido líder',
		price: 329.99,
		images: [
			{
				id: 'img-e16-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Bose QuietComfort 45',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.9, count: 140 },
	},
	{
		id: 'prod-e17',
		name: 'LG OLED C2',
		description: 'TV OLED 65" con tecnología de vanguardia',
		price: 2499.99,
		images: [
			{
				id: 'img-e17-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'LG OLED C2',
				isMain: true,
			},
		],
		stock: 8,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.9, count: 65 },
	},
	{
		id: 'prod-e18',
		name: 'Fitbit Sense 2',
		description: 'Reloj inteligente avanzado para fitness',
		price: 299.99,
		images: [
			{
				id: 'img-e18-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Fitbit Sense 2',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.6, count: 88 },
	},
	{
		id: 'prod-e19',
		name: 'Canon EOS R6',
		description: 'Cámara mirrorless profesional',
		price: 2499.99,
		images: [
			{
				id: 'img-e19-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Canon EOS R6',
				isMain: true,
			},
		],
		stock: 12,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.9, count: 72 },
	},
	{
		id: 'prod-e20',
		name: 'Razer Blade 15',
		description: 'Laptop gaming con RTX 3080',
		price: 1999.99,
		images: [
			{
				id: 'img-e20-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Razer Blade 15',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-1',
		category: categories[0],
		rating: { rate: 4.8, count: 95 },
	},
];

const ropa: Product[] = [
	{
		id: 'prod-r1',
		name: 'Camisa Casual',
		description: 'Camisa casual de algodón para hombre, cómoda y versátil',
		price: 29.99,
		images: [
			{
				id: 'img-r1-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Camisa Casual',
				isMain: true,
			},
		],
		stock: 100,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.5, count: 85 },
	},
	{
		id: 'prod-r2',
		name: 'Vestido Floral',
		description:
			'Vestido elegante con estampado floral, perfecto para ocasiones especiales',
		price: 49.99,
		images: [
			{
				id: 'img-r2-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Vestido Floral',
				isMain: true,
			},
		],
		stock: 75,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.6, count: 92 },
	},
	{
		id: 'prod-r3',
		name: 'Jeans Slim Fit',
		description: 'Jeans modernos con corte slim fit, alta elasticidad',
		price: 39.99,
		images: [
			{
				id: 'img-r3-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Jeans Slim Fit',
				isMain: true,
			},
		],
		stock: 120,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.7, count: 150 },
	},
	{
		id: 'prod-r4',
		name: 'Blazer Elegante',
		description: 'Blazer de corte recto, ideal para ocasiones formales',
		price: 89.99,
		images: [
			{
				id: 'img-r4-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Blazer Elegante',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.8, count: 68 },
	},
	{
		id: 'prod-r5',
		name: 'Sudadera con Capucha',
		description: 'Sudadera casual con capucha, perfecta para el día a día',
		price: 34.99,
		images: [
			{
				id: 'img-r5-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Sudadera con Capucha',
				isMain: true,
			},
		],
		stock: 85,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.6, count: 120 },
	},
	{
		id: 'prod-r6',
		name: 'Falda Plisada',
		description: 'Falda plisada de poliéster, elegante y versátil',
		price: 29.99,
		images: [
			{
				id: 'img-r6-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Falda Plisada',
				isMain: true,
			},
		],
		stock: 60,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.5, count: 75 },
	},
	{
		id: 'prod-r7',
		name: 'Camiseta Básica',
		description: 'Pack de 3 camisetas básicas de algodón',
		price: 24.99,
		images: [
			{
				id: 'img-r7-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Camiseta Básica',
				isMain: true,
			},
		],
		stock: 200,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.7, count: 180 },
	},
	{
		id: 'prod-r8',
		name: 'Traje Formal',
		description: 'Traje de dos piezas, corte clásico',
		price: 199.99,
		images: [
			{
				id: 'img-r8-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Traje Formal',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.8, count: 45 },
	},
	{
		id: 'prod-r9',
		name: 'Chaqueta de Cuero',
		description: 'Chaqueta de cuero sintético, estilo motero',
		price: 79.99,
		images: [
			{
				id: 'img-r9-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Chaqueta de Cuero',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.6, count: 88 },
	},
	{
		id: 'prod-r10',
		name: 'Polo Casual',
		description: 'Polo de piqué de algodón, cuello ribeteado',
		price: 32.99,
		images: [
			{
				id: 'img-r10-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Polo Casual',
				isMain: true,
			},
		],
		stock: 90,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.5, count: 110 },
	},
	{
		id: 'prod-r11',
		name: 'Vestido de Noche',
		description: 'Vestido largo para ocasiones especiales',
		price: 129.99,
		images: [
			{
				id: 'img-r11-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Vestido de Noche',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.9, count: 55 },
	},
	{
		id: 'prod-r12',
		name: 'Pantalón Chino',
		description: 'Pantalón chino de algodón, corte recto',
		price: 44.99,
		images: [
			{
				id: 'img-r12-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Pantalón Chino',
				isMain: true,
			},
		],
		stock: 70,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.7, count: 95 },
	},
	{
		id: 'prod-r13',
		name: 'Blusa de Seda',
		description: 'Blusa de seda natural, elegante y suave',
		price: 59.99,
		images: [
			{
				id: 'img-r13-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Blusa de Seda',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.8, count: 65 },
	},
	{
		id: 'prod-r14',
		name: 'Chaleco Acolchado',
		description: 'Chaleco acolchado, ideal para temporada fría',
		price: 69.99,
		images: [
			{
				id: 'img-r14-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Chaleco Acolchado',
				isMain: true,
			},
		],
		stock: 50,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.6, count: 82 },
	},
	{
		id: 'prod-r15',
		name: 'Falda Lápiz',
		description: 'Falda lápiz de punto, corte ajustado',
		price: 39.99,
		images: [
			{
				id: 'img-r15-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Falda Lápiz',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.7, count: 70 },
	},
	{
		id: 'prod-r16',
		name: 'Camisa Oxford',
		description: 'Camisa Oxford de algodón, cuello button-down',
		price: 49.99,
		images: [
			{
				id: 'img-r16-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Camisa Oxford',
				isMain: true,
			},
		],
		stock: 60,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.8, count: 90 },
	},
	{
		id: 'prod-r17',
		name: 'Vestido Casual',
		description: 'Vestido casual de punto, cómodo y versátil',
		price: 45.99,
		images: [
			{
				id: 'img-r17-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Vestido Casual',
				isMain: true,
			},
		],
		stock: 55,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.6, count: 78 },
	},
	{
		id: 'prod-r18',
		name: 'Pantalón de Vestir',
		description: 'Pantalón de vestir de corte recto, tela premium',
		price: 79.99,
		images: [
			{
				id: 'img-r18-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Pantalón de Vestir',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.7, count: 85 },
	},
	{
		id: 'prod-r19',
		name: 'Top de Encaje',
		description: 'Top de encaje, elegante y versátil',
		price: 34.99,
		images: [
			{
				id: 'img-r19-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Top de Encaje',
				isMain: true,
			},
		],
		stock: 65,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.5, count: 92 },
	},
	{
		id: 'prod-r20',
		name: 'Abrigo de Lana',
		description: 'Abrigo de lana, perfecto para invierno',
		price: 149.99,
		images: [
			{
				id: 'img-r20-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Abrigo de Lana',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-2',
		category: categories[1],
		rating: { rate: 4.8, count: 75 },
	},
];

const hogar: Product[] = [
	{
		id: 'prod-h1',
		name: 'Lámpara LED',
		description: 'Lámpara LED moderna para sala de estar, luz ajustable',
		price: 49.99,
		images: [
			{
				id: 'img-h1-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Lámpara LED',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.3, count: 60 },
	},
	{
		id: 'prod-h2',
		name: 'Set de Sábanas',
		description: 'Set de sábanas de algodón egipcio, 600 hilos',
		price: 39.99,
		images: [
			{
				id: 'img-h2-1',
				url: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg',
				alt: 'Set de Sábanas',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.4, count: 55 },
	},
	{
		id: 'prod-h3',
		name: 'Juego de Ollas',
		description: 'Set de 5 ollas antiadherentes con tapa',
		price: 89.99,
		images: [
			{
				id: 'img-h3-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Juego de Ollas',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.7, count: 85 },
	},
	{
		id: 'prod-h4',
		name: 'Cafetera Programable',
		description: 'Cafetera de goteo con temporizador y filtro permanente',
		price: 59.99,
		images: [
			{
				id: 'img-h4-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Cafetera Programable',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.6, count: 120 },
	},
	{
		id: 'prod-h5',
		name: 'Aspiradora Robot',
		description: 'Aspiradora robot inteligente con mapeo de habitaciones',
		price: 299.99,
		images: [
			{
				id: 'img-h5-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Aspiradora Robot',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.8, count: 95 },
	},
	{
		id: 'prod-h6',
		name: 'Set de Toallas',
		description: 'Set de 6 toallas de baño de algodón premium',
		price: 34.99,
		images: [
			{
				id: 'img-h6-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Toallas',
				isMain: true,
			},
		],
		stock: 50,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.5, count: 88 },
	},
	{
		id: 'prod-h7',
		name: 'Cortinas Blackout',
		description: 'Cortinas blackout para dormitorio, bloqueo total de luz',
		price: 69.99,
		images: [
			{
				id: 'img-h7-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Cortinas Blackout',
				isMain: true,
			},
		],
		stock: 20,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.7, count: 65 },
	},
	{
		id: 'prod-h8',
		name: 'Vajilla Completa',
		description: 'Vajilla de porcelana para 12 personas',
		price: 149.99,
		images: [
			{
				id: 'img-h8-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Vajilla Completa',
				isMain: true,
			},
		],
		stock: 12,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.9, count: 45 },
	},
	{
		id: 'prod-h9',
		name: 'Batidora Profesional',
		description: 'Batidora de pie con 10 velocidades y accesorios',
		price: 79.99,
		images: [
			{
				id: 'img-h9-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Batidora Profesional',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.6, count: 110 },
	},
	{
		id: 'prod-h10',
		name: 'Alfombra Persa',
		description: 'Alfombra persa de lana, diseño tradicional',
		price: 199.99,
		images: [
			{
				id: 'img-h10-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Alfombra Persa',
				isMain: true,
			},
		],
		stock: 8,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.8, count: 35 },
	},
	{
		id: 'prod-h11',
		name: 'Set de Cubiertos',
		description: 'Set de cubiertos de acero inoxidable para 8 personas',
		price: 89.99,
		images: [
			{
				id: 'img-h11-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Cubiertos',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.7, count: 75 },
	},
	{
		id: 'prod-h12',
		name: 'Lámpara de Mesa',
		description: 'Lámpara de mesa LED con brazo ajustable',
		price: 39.99,
		images: [
			{
				id: 'img-h12-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Lámpara de Mesa',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.5, count: 82 },
	},
	{
		id: 'prod-h13',
		name: 'Horno Eléctrico',
		description: 'Horno eléctrico de convección con 6 funciones',
		price: 129.99,
		images: [
			{
				id: 'img-h13-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Horno Eléctrico',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.8, count: 68 },
	},
	{
		id: 'prod-h14',
		name: 'Set de Cojines',
		description: 'Set de 4 cojines decorativos para sofá',
		price: 44.99,
		images: [
			{
				id: 'img-h14-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Cojines',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.6, count: 55 },
	},
	{
		id: 'prod-h15',
		name: 'Máquina de Café Espresso',
		description: 'Máquina de café espresso automática con molinillo',
		price: 249.99,
		images: [
			{
				id: 'img-h15-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Máquina de Café Espresso',
				isMain: true,
			},
		],
		stock: 10,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.9, count: 42 },
	},
	{
		id: 'prod-h16',
		name: 'Set de Ollas de Presión',
		description: 'Set de 3 ollas de presión de acero inoxidable',
		price: 119.99,
		images: [
			{
				id: 'img-h16-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Ollas de Presión',
				isMain: true,
			},
		],
		stock: 18,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.7, count: 58 },
	},
	{
		id: 'prod-h17',
		name: 'Lámpara de Techo',
		description: 'Lámpara de techo LED con diseño moderno',
		price: 79.99,
		images: [
			{
				id: 'img-h17-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Lámpara de Techo',
				isMain: true,
			},
		],
		stock: 22,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.6, count: 48 },
	},
	{
		id: 'prod-h18',
		name: 'Set de Utensilios de Cocina',
		description: 'Set de 15 utensilios de cocina de acero inoxidable',
		price: 54.99,
		images: [
			{
				id: 'img-h18-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Utensilios de Cocina',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.8, count: 92 },
	},
	{
		id: 'prod-h19',
		name: 'Mesa de Centro',
		description: 'Mesa de centro de madera maciza con diseño moderno',
		price: 179.99,
		images: [
			{
				id: 'img-h19-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Mesa de Centro',
				isMain: true,
			},
		],
		stock: 12,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.7, count: 38 },
	},
	{
		id: 'prod-h20',
		name: 'Set de Sartenes',
		description: 'Set de 5 sartenes antiadherentes con mango ergonómico',
		price: 99.99,
		images: [
			{
				id: 'img-h20-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Sartenes',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-3',
		category: categories[2],
		rating: { rate: 4.8, count: 85 },
	},
];

const joyeria: Product[] = [
	{
		id: 'prod-j1',
		name: 'Anillo de Diamantes',
		description: 'Anillo de compromiso con diamante central de 1 quilate',
		price: 2999.99,
		images: [
			{
				id: 'img-j1-1',
				url: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
				alt: 'Anillo de Diamantes',
				isMain: true,
			},
		],
		stock: 5,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.9, count: 45 },
	},
	{
		id: 'prod-j2',
		name: 'Collar de Perlas',
		description: 'Collar de perlas cultivadas de agua dulce, 18 pulgadas',
		price: 199.99,
		images: [
			{
				id: 'img-j2-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Collar de Perlas',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.7, count: 68 },
	},
	{
		id: 'prod-j3',
		name: 'Pendientes de Oro',
		description: 'Pendientes de oro 14k con diseño minimalista',
		price: 149.99,
		images: [
			{
				id: 'img-j3-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Pendientes de Oro',
				isMain: true,
			},
		],
		stock: 20,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.8, count: 92 },
	},
	{
		id: 'prod-j4',
		name: 'Brazalete de Plata',
		description: 'Brazalete de plata esterlina con diseño trenzado',
		price: 89.99,
		images: [
			{
				id: 'img-j4-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Brazalete de Plata',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.6, count: 75 },
	},
	{
		id: 'prod-j5',
		name: 'Set de Joyería de Rubíes',
		description: 'Set completo con collar, pendientes y anillo de rubíes',
		price: 799.99,
		images: [
			{
				id: 'img-j5-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Joyería de Rubíes',
				isMain: true,
			},
		],
		stock: 8,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.9, count: 35 },
	},
	{
		id: 'prod-j6',
		name: 'Reloj de Lujo',
		description: 'Reloj automático con correa de cuero genuino',
		price: 599.99,
		images: [
			{
				id: 'img-j6-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Reloj de Lujo',
				isMain: true,
			},
		],
		stock: 12,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.8, count: 58 },
	},
	{
		id: 'prod-j7',
		name: 'Aretes de Zafiro',
		description: 'Aretes de zafiro azul con montura de oro blanco',
		price: 349.99,
		images: [
			{
				id: 'img-j7-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Aretes de Zafiro',
				isMain: true,
			},
		],
		stock: 10,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.7, count: 42 },
	},
	{
		id: 'prod-j8',
		name: 'Collar de Esmeraldas',
		description: 'Collar de esmeraldas colombianas con oro 18k',
		price: 1499.99,
		images: [
			{
				id: 'img-j8-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Collar de Esmeraldas',
				isMain: true,
			},
		],
		stock: 3,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.9, count: 28 },
	},
	{
		id: 'prod-j9',
		name: 'Anillo de Compromiso Vintage',
		description: 'Anillo de compromiso estilo vintage con diamantes',
		price: 899.99,
		images: [
			{
				id: 'img-j9-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Anillo de Compromiso Vintage',
				isMain: true,
			},
		],
		stock: 7,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.8, count: 52 },
	},
	{
		id: 'prod-j10',
		name: 'Pulsera de Pandora',
		description: 'Pulsera de plata con charms personalizables',
		price: 129.99,
		images: [
			{
				id: 'img-j10-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Pulsera de Pandora',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.6, count: 88 },
	},
	{
		id: 'prod-j11',
		name: 'Set de Joyería de Perlas',
		description: 'Set completo de perlas cultivadas con detalles en oro',
		price: 299.99,
		images: [
			{
				id: 'img-j11-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Joyería de Perlas',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.7, count: 65 },
	},
	{
		id: 'prod-j12',
		name: 'Anillo de Zafiro',
		description: 'Anillo de zafiro azul con diamantes laterales',
		price: 599.99,
		images: [
			{
				id: 'img-j12-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Anillo de Zafiro',
				isMain: true,
			},
		],
		stock: 8,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.8, count: 48 },
	},
	{
		id: 'prod-j13',
		name: 'Collar de Diamantes',
		description: 'Collar de diamantes con diseño de cascada',
		price: 1999.99,
		images: [
			{
				id: 'img-j13-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Collar de Diamantes',
				isMain: true,
			},
		],
		stock: 4,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.9, count: 32 },
	},
	{
		id: 'prod-j14',
		name: 'Aretes de Perlas',
		description: 'Aretes de perlas cultivadas con montura de oro',
		price: 79.99,
		images: [
			{
				id: 'img-j14-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Aretes de Perlas',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.6, count: 95 },
	},
	{
		id: 'prod-j15',
		name: 'Brazalete de Diamantes',
		description: 'Brazalete de oro blanco con diamantes engastados',
		price: 899.99,
		images: [
			{
				id: 'img-j15-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Brazalete de Diamantes',
				isMain: true,
			},
		],
		stock: 6,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.8, count: 42 },
	},
	{
		id: 'prod-j16',
		name: 'Anillo de Esmeralda',
		description: 'Anillo de esmeralda colombiana con diamantes',
		price: 1299.99,
		images: [
			{
				id: 'img-j16-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Anillo de Esmeralda',
				isMain: true,
			},
		],
		stock: 5,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.9, count: 38 },
	},
	{
		id: 'prod-j17',
		name: 'Collar de Rubíes',
		description: 'Collar de rubíes birmanos con oro amarillo',
		price: 799.99,
		images: [
			{
				id: 'img-j17-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Collar de Rubíes',
				isMain: true,
			},
		],
		stock: 7,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.7, count: 45 },
	},
	{
		id: 'prod-j18',
		name: 'Set de Joyería de Zafiros',
		description: 'Set completo con collar, pendientes y anillo de zafiros',
		price: 999.99,
		images: [
			{
				id: 'img-j18-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Joyería de Zafiros',
				isMain: true,
			},
		],
		stock: 5,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.8, count: 35 },
	},
	{
		id: 'prod-j19',
		name: 'Pendientes de Diamantes',
		description: 'Pendientes de diamantes con diseño de gota',
		price: 449.99,
		images: [
			{
				id: 'img-j19-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Pendientes de Diamantes',
				isMain: true,
			},
		],
		stock: 12,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.9, count: 68 },
	},
	{
		id: 'prod-j20',
		name: 'Collar de Oro',
		description: 'Collar de oro 18k con diseño moderno',
		price: 399.99,
		images: [
			{
				id: 'img-j20-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Collar de Oro',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-4',
		category: categories[3],
		rating: { rate: 4.7, count: 82 },
	},
];

const deportes: Product[] = [
	{
		id: 'prod-d1',
		name: 'Balón de Fútbol Profesional',
		description: 'Balón de fútbol talla 5, material sintético de alta calidad',
		price: 49.99,
		images: [
			{
				id: 'img-d1-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Balón de Fútbol Profesional',
				isMain: true,
			},
		],
		stock: 50,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.7, count: 120 },
	},
	{
		id: 'prod-d2',
		name: 'Raqueta de Tenis',
		description: 'Raqueta de tenis profesional con encordado incluido',
		price: 129.99,
		images: [
			{
				id: 'img-d2-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Raqueta de Tenis',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.8, count: 85 },
	},
	{
		id: 'prod-d3',
		name: 'Bicicleta de Montaña',
		description: 'Bicicleta de montaña con 21 velocidades y suspensión',
		price: 499.99,
		images: [
			{
				id: 'img-d3-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Bicicleta de Montaña',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.9, count: 65 },
	},
	{
		id: 'prod-d4',
		name: 'Set de Pesas',
		description: 'Set de pesas ajustables de 5-25kg con barra',
		price: 149.99,
		images: [
			{
				id: 'img-d4-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Pesas',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.6, count: 95 },
	},
	{
		id: 'prod-d5',
		name: 'Treadmill Eléctrico',
		description:
			'Cinta de correr eléctrica con pantalla LCD y programas preestablecidos',
		price: 799.99,
		images: [
			{
				id: 'img-d5-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Treadmill Eléctrico',
				isMain: true,
			},
		],
		stock: 10,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.8, count: 45 },
	},
	{
		id: 'prod-d6',
		name: 'Balón de Baloncesto',
		description: 'Balón de baloncesto talla 7, material de cuero sintético',
		price: 39.99,
		images: [
			{
				id: 'img-d6-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Balón de Baloncesto',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.7, count: 88 },
	},
	{
		id: 'prod-d7',
		name: 'Tabla de Surf',
		description: 'Tabla de surf de espuma para principiantes',
		price: 299.99,
		images: [
			{
				id: 'img-d7-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Tabla de Surf',
				isMain: true,
			},
		],
		stock: 12,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.5, count: 35 },
	},
	{
		id: 'prod-d8',
		name: 'Set de Golf',
		description: 'Set completo de golf con bolsa y 12 palos',
		price: 599.99,
		images: [
			{
				id: 'img-d8-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Golf',
				isMain: true,
			},
		],
		stock: 8,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.9, count: 42 },
	},
	{
		id: 'prod-d9',
		name: 'Raqueta de Bádminton',
		description: 'Raqueta de bádminton profesional con funda',
		price: 69.99,
		images: [
			{
				id: 'img-d9-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Raqueta de Bádminton',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.6, count: 75 },
	},
	{
		id: 'prod-d10',
		name: 'Mancuernas Ajustables',
		description: 'Par de mancuernas ajustables de 2.5-25kg',
		price: 89.99,
		images: [
			{
				id: 'img-d10-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Mancuernas Ajustables',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.7, count: 110 },
	},
	{
		id: 'prod-d11',
		name: 'Bicicleta Estática',
		description: 'Bicicleta estática con monitor de ritmo cardíaco',
		price: 299.99,
		images: [
			{
				id: 'img-d11-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Bicicleta Estática',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.8, count: 68 },
	},
	{
		id: 'prod-d12',
		name: 'Balón de Voleibol',
		description: 'Balón de voleibol oficial de competición',
		price: 34.99,
		images: [
			{
				id: 'img-d12-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Balón de Voleibol',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.6, count: 82 },
	},
	{
		id: 'prod-d13',
		name: 'Set de Yoga',
		description: 'Set completo de yoga con mat, bloques y correa',
		price: 49.99,
		images: [
			{
				id: 'img-d13-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Yoga',
				isMain: true,
			},
		],
		stock: 60,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.9, count: 150 },
	},
	{
		id: 'prod-d14',
		name: 'Raqueta de Pádel',
		description: 'Raqueta de pádel profesional con funda',
		price: 159.99,
		images: [
			{
				id: 'img-d14-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Raqueta de Pádel',
				isMain: true,
			},
		],
		stock: 20,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.7, count: 58 },
	},
	{
		id: 'prod-d15',
		name: 'Máquina de Remo',
		description: 'Máquina de remo plegable con resistencia magnética',
		price: 399.99,
		images: [
			{
				id: 'img-d15-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Máquina de Remo',
				isMain: true,
			},
		],
		stock: 12,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.8, count: 45 },
	},
	{
		id: 'prod-d16',
		name: 'Balón de Rugby',
		description: 'Balón de rugby talla 5, material sintético',
		price: 44.99,
		images: [
			{
				id: 'img-d16-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Balón de Rugby',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.6, count: 65 },
	},
	{
		id: 'prod-d17',
		name: 'Set de Boxeo',
		description: 'Set completo de boxeo con guantes, saco y vendas',
		price: 129.99,
		images: [
			{
				id: 'img-d17-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Boxeo',
				isMain: true,
			},
		],
		stock: 18,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.7, count: 72 },
	},
	{
		id: 'prod-d18',
		name: 'Raqueta de Squash',
		description: 'Raqueta de squash profesional con cordaje',
		price: 79.99,
		images: [
			{
				id: 'img-d18-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Raqueta de Squash',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.5, count: 48 },
	},
	{
		id: 'prod-d19',
		name: 'Máquina de Ejercicios Multifunción',
		description: 'Máquina de ejercicios para todo el cuerpo con 10 estaciones',
		price: 899.99,
		images: [
			{
				id: 'img-d19-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Máquina de Ejercicios Multifunción',
				isMain: true,
			},
		],
		stock: 8,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.9, count: 35 },
	},
	{
		id: 'prod-d20',
		name: 'Set de Tenis de Mesa',
		description: 'Set completo de tenis de mesa con mesa, redes y paletas',
		price: 199.99,
		images: [
			{
				id: 'img-d20-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Tenis de Mesa',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-5',
		category: categories[4],
		rating: { rate: 4.8, count: 55 },
	},
];

const libros: Product[] = [
	{
		id: 'prod-l1',
		name: 'El Señor de los Anillos',
		description: 'Trilogía completa de El Señor de los Anillos en tapa dura',
		price: 49.99,
		images: [
			{
				id: 'img-l1-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'El Señor de los Anillos',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.9, count: 250 },
	},
	{
		id: 'prod-l2',
		name: 'Cien Años de Soledad',
		description:
			'Edición especial de la obra maestra de Gabriel García Márquez',
		price: 24.99,
		images: [
			{
				id: 'img-l2-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Cien Años de Soledad',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.8, count: 180 },
	},
	{
		id: 'prod-l3',
		name: 'Harry Potter Colección Completa',
		description: 'Los 7 libros de la saga Harry Potter en tapa dura',
		price: 89.99,
		images: [
			{
				id: 'img-l3-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Harry Potter Colección Completa',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.9, count: 320 },
	},
	{
		id: 'prod-l4',
		name: 'El Principito',
		description: 'Edición ilustrada del clásico de Antoine de Saint-Exupéry',
		price: 19.99,
		images: [
			{
				id: 'img-l4-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'El Principito',
				isMain: true,
			},
		],
		stock: 60,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.9, count: 200 },
	},
	{
		id: 'prod-l5',
		name: '1984',
		description: 'Distopía clásica de George Orwell en edición especial',
		price: 22.99,
		images: [
			{
				id: 'img-l5-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: '1984',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.8, count: 165 },
	},
	{
		id: 'prod-l6',
		name: 'El Alquimista',
		description: 'Bestseller de Paulo Coelho en tapa blanda',
		price: 18.99,
		images: [
			{
				id: 'img-l6-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'El Alquimista',
				isMain: true,
			},
		],
		stock: 55,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.7, count: 145 },
	},
	{
		id: 'prod-l7',
		name: 'Los Juegos del Hambre',
		description: 'Trilogía completa de Los Juegos del Hambre',
		price: 39.99,
		images: [
			{
				id: 'img-l7-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Los Juegos del Hambre',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.8, count: 190 },
	},
	{
		id: 'prod-l8',
		name: 'El Código Da Vinci',
		description: 'Thriller de Dan Brown en edición de bolsillo',
		price: 15.99,
		images: [
			{
				id: 'img-l8-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'El Código Da Vinci',
				isMain: true,
			},
		],
		stock: 50,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.6, count: 130 },
	},
	{
		id: 'prod-l9',
		name: 'Orgullo y Prejuicio',
		description: 'Clásico de Jane Austen en edición especial',
		price: 21.99,
		images: [
			{
				id: 'img-l9-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Orgullo y Prejuicio',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.9, count: 175 },
	},
	{
		id: 'prod-l10',
		name: 'El Hobbit',
		description: 'Edición ilustrada de El Hobbit de J.R.R. Tolkien',
		price: 29.99,
		images: [
			{
				id: 'img-l10-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'El Hobbit',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.8, count: 155 },
	},
	{
		id: 'prod-l11',
		name: 'Crónica de una Muerte Anunciada',
		description: 'Novela de Gabriel García Márquez en tapa blanda',
		price: 16.99,
		images: [
			{
				id: 'img-l11-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Crónica de una Muerte Anunciada',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.7, count: 120 },
	},
	{
		id: 'prod-l12',
		name: 'El Arte de la Guerra',
		description: 'Tratado militar de Sun Tzu con comentarios',
		price: 19.99,
		images: [
			{
				id: 'img-l12-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'El Arte de la Guerra',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.8, count: 140 },
	},
	{
		id: 'prod-l13',
		name: 'Los Miserables',
		description: 'Obra maestra de Victor Hugo en edición completa',
		price: 34.99,
		images: [
			{
				id: 'img-l13-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Los Miserables',
				isMain: true,
			},
		],
		stock: 20,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.9, count: 95 },
	},
	{
		id: 'prod-l14',
		name: 'El Retrato de Dorian Gray',
		description: 'Clásico de Oscar Wilde en edición especial',
		price: 22.99,
		images: [
			{
				id: 'img-l14-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'El Retrato de Dorian Gray',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.8, count: 110 },
	},
	{
		id: 'prod-l15',
		name: 'Don Quijote de la Mancha',
		description: 'Edición conmemorativa de la obra de Cervantes',
		price: 39.99,
		images: [
			{
				id: 'img-l15-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Don Quijote de la Mancha',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.9, count: 85 },
	},
	{
		id: 'prod-l16',
		name: 'El Gran Gatsby',
		description: 'Clásico de F. Scott Fitzgerald en tapa dura',
		price: 24.99,
		images: [
			{
				id: 'img-l16-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'El Gran Gatsby',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.8, count: 150 },
	},
	{
		id: 'prod-l17',
		name: 'Rayuela',
		description: 'Obra maestra de Julio Cortázar en edición especial',
		price: 27.99,
		images: [
			{
				id: 'img-l17-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Rayuela',
				isMain: true,
			},
		],
		stock: 28,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.7, count: 125 },
	},
	{
		id: 'prod-l18',
		name: 'El Nombre del Viento',
		description: 'Primer libro de la trilogía Crónica del Asesino de Reyes',
		price: 29.99,
		images: [
			{
				id: 'img-l18-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'El Nombre del Viento',
				isMain: true,
			},
		],
		stock: 22,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.9, count: 180 },
	},
	{
		id: 'prod-l19',
		name: 'Los Pilares de la Tierra',
		description: 'Épica medieval de Ken Follett en tapa dura',
		price: 32.99,
		images: [
			{
				id: 'img-l19-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Los Pilares de la Tierra',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.8, count: 160 },
	},
	{
		id: 'prod-l20',
		name: 'El Amor en los Tiempos del Cólera',
		description: 'Novela de Gabriel García Márquez en edición especial',
		price: 23.99,
		images: [
			{
				id: 'img-l20-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'El Amor en los Tiempos del Cólera',
				isMain: true,
			},
		],
		stock: 38,
		categoryId: 'cat-6',
		category: categories[5],
		rating: { rate: 4.9, count: 145 },
	},
];

const belleza: Product[] = [
	{
		id: 'prod-b1',
		name: 'Set de Maquillaje Profesional',
		description:
			'Set completo de maquillaje con 24 sombras, labiales y brochas',
		price: 89.99,
		images: [
			{
				id: 'img-b1-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Maquillaje Profesional',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.8, count: 145 },
	},
	{
		id: 'prod-b2',
		name: 'Crema Hidratante Facial',
		description: 'Crema hidratante con ácido hialurónico y vitamina E',
		price: 34.99,
		images: [
			{
				id: 'img-b2-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Crema Hidratante Facial',
				isMain: true,
			},
		],
		stock: 50,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.7, count: 180 },
	},
	{
		id: 'prod-b3',
		name: 'Perfume de Lujo',
		description: 'Perfume floral con notas de jazmín y vainilla',
		price: 129.99,
		images: [
			{
				id: 'img-b3-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Perfume de Lujo',
				isMain: true,
			},
		],
		stock: 20,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.9, count: 95 },
	},
	{
		id: 'prod-b4',
		name: 'Kit de Cuidado Capilar',
		description:
			'Set de champú, acondicionador y mascarilla para cabello dañado',
		price: 49.99,
		images: [
			{
				id: 'img-b4-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Kit de Cuidado Capilar',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.6, count: 120 },
	},
	{
		id: 'prod-b5',
		name: 'Paleta de Sombras',
		description: 'Paleta de 18 sombras mate y brillantes',
		price: 39.99,
		images: [
			{
				id: 'img-b5-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Paleta de Sombras',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.8, count: 160 },
	},
	{
		id: 'prod-b6',
		name: 'Serum Facial Vitamina C',
		description: 'Serum antioxidante con vitamina C pura',
		price: 45.99,
		images: [
			{
				id: 'img-b6-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Serum Facial Vitamina C',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.9, count: 110 },
	},
	{
		id: 'prod-b7',
		name: 'Set de Brochas Profesionales',
		description: 'Set de 12 brochas de maquillaje de pelo sintético',
		price: 29.99,
		images: [
			{
				id: 'img-b7-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Brochas Profesionales',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.7, count: 135 },
	},
	{
		id: 'prod-b8',
		name: 'Mascarilla Facial',
		description: 'Mascarilla de arcilla purificante para piel mixta',
		price: 24.99,
		images: [
			{
				id: 'img-b8-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Mascarilla Facial',
				isMain: true,
			},
		],
		stock: 55,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.6, count: 95 },
	},
	{
		id: 'prod-b9',
		name: 'Labial Mate',
		description: 'Labial mate de larga duración en 6 tonos',
		price: 19.99,
		images: [
			{
				id: 'img-b9-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Labial Mate',
				isMain: true,
			},
		],
		stock: 60,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.8, count: 150 },
	},
	{
		id: 'prod-b10',
		name: 'Kit de Cuidado Facial',
		description:
			'Set completo de limpieza facial con limpiador, tónico y crema',
		price: 59.99,
		images: [
			{
				id: 'img-b10-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Kit de Cuidado Facial',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.9, count: 85 },
	},
	{
		id: 'prod-b11',
		name: 'Base de Maquillaje',
		description: 'Base de maquillaje de larga duración con SPF',
		price: 42.99,
		images: [
			{
				id: 'img-b11-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Base de Maquillaje',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.7, count: 125 },
	},
	{
		id: 'prod-b12',
		name: 'Set de Uñas',
		description: 'Kit completo de manicura con esmaltes y accesorios',
		price: 34.99,
		images: [
			{
				id: 'img-b12-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Uñas',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.6, count: 105 },
	},
	{
		id: 'prod-b13',
		name: 'Contorno de Ojos',
		description: 'Contorno de ojos con efecto anti-fatiga',
		price: 27.99,
		images: [
			{
				id: 'img-b13-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Contorno de Ojos',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.8, count: 115 },
	},
	{
		id: 'prod-b14',
		name: 'Set de Fragancias',
		description: 'Colección de 5 mini perfumes de lujo',
		price: 79.99,
		images: [
			{
				id: 'img-b14-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Fragancias',
				isMain: true,
			},
		],
		stock: 20,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.9, count: 75 },
	},
	{
		id: 'prod-b15',
		name: 'Máscara de Pestañas',
		description: 'Máscara de pestañas volumizadora y alargadora',
		price: 22.99,
		images: [
			{
				id: 'img-b15-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Máscara de Pestañas',
				isMain: true,
			},
		],
		stock: 50,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.7, count: 140 },
	},
	{
		id: 'prod-b16',
		name: 'Kit de Cuidado Corporal',
		description: 'Set de cremas y aceites para el cuerpo',
		price: 54.99,
		images: [
			{
				id: 'img-b16-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Kit de Cuidado Corporal',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.8, count: 90 },
	},
	{
		id: 'prod-b17',
		name: 'Paleta de Rubor',
		description: 'Paleta de 6 tonos de rubor mate y brillante',
		price: 32.99,
		images: [
			{
				id: 'img-b17-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Paleta de Rubor',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.6, count: 100 },
	},
	{
		id: 'prod-b18',
		name: 'Set de Cuidado Capilar Premium',
		description: 'Kit de tratamiento capilar con productos profesionales',
		price: 69.99,
		images: [
			{
				id: 'img-b18-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Cuidado Capilar Premium',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.9, count: 80 },
	},
	{
		id: 'prod-b19',
		name: 'Esmaltes de Uñas',
		description: 'Set de 6 esmaltes de uñas de larga duración',
		price: 24.99,
		images: [
			{
				id: 'img-b19-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Esmaltes de Uñas',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.7, count: 130 },
	},
	{
		id: 'prod-b20',
		name: 'Kit de Maquillaje para Ojos',
		description:
			'Set completo de maquillaje para ojos con sombras y delineadores',
		price: 44.99,
		images: [
			{
				id: 'img-b20-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Kit de Maquillaje para Ojos',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-7',
		category: categories[6],
		rating: { rate: 4.8, count: 120 },
	},
];

const juguetes: Product[] = [
	{
		id: 'prod-t1',
		name: 'Lego Star Wars',
		description: 'Set de construcción Lego Star Wars con 1000 piezas',
		price: 79.99,
		images: [
			{
				id: 'img-t1-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Lego Star Wars',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.9, count: 180 },
	},
	{
		id: 'prod-t2',
		name: 'Barbie Dreamhouse',
		description: 'Casa de muñecas Barbie con 3 pisos y accesorios',
		price: 149.99,
		images: [
			{
				id: 'img-t2-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Barbie Dreamhouse',
				isMain: true,
			},
		],
		stock: 15,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.8, count: 95 },
	},
	{
		id: 'prod-t3',
		name: 'Monopoly Edición Especial',
		description: 'Juego de mesa Monopoly con temática de ciudades famosas',
		price: 39.99,
		images: [
			{
				id: 'img-t3-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Monopoly Edición Especial',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.7, count: 120 },
	},
	{
		id: 'prod-t4',
		name: 'Robot Educativo',
		description: 'Robot programable para aprender codificación básica',
		price: 89.99,
		images: [
			{
				id: 'img-t4-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Robot Educativo',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.8, count: 85 },
	},
	{
		id: 'prod-t5',
		name: 'Set de Construcción Magnético',
		description:
			'Juego de construcción con piezas magnéticas para crear estructuras 3D',
		price: 49.99,
		images: [
			{
				id: 'img-t5-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Construcción Magnético',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.9, count: 110 },
	},
	{
		id: 'prod-t6',
		name: 'Muñeca Interactiva',
		description: 'Muñeca que habla y responde a estímulos',
		price: 59.99,
		images: [
			{
				id: 'img-t6-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Muñeca Interactiva',
				isMain: true,
			},
		],
		stock: 20,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.6, count: 75 },
	},
	{
		id: 'prod-t7',
		name: 'Juego de Química',
		description: 'Set de experimentos químicos para niños con guía educativa',
		price: 44.99,
		images: [
			{
				id: 'img-t7-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Juego de Química',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.7, count: 90 },
	},
	{
		id: 'prod-t8',
		name: 'Figura de Acción Coleccionable',
		description: 'Figura de acción detallada con accesorios',
		price: 29.99,
		images: [
			{
				id: 'img-t8-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Figura de Acción Coleccionable',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.8, count: 65 },
	},
	{
		id: 'prod-t9',
		name: 'Juego de Mesa Familiar',
		description: 'Juego de mesa para toda la familia con preguntas y desafíos',
		price: 34.99,
		images: [
			{
				id: 'img-t9-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Juego de Mesa Familiar',
				isMain: true,
			},
		],
		stock: 50,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.7, count: 140 },
	},
	{
		id: 'prod-t10',
		name: 'Set de Arte Creativo',
		description: 'Kit completo de arte con pinturas, pinceles y lienzos',
		price: 39.99,
		images: [
			{
				id: 'img-t10-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Arte Creativo',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.8, count: 95 },
	},
	{
		id: 'prod-t11',
		name: 'Pista de Carreras',
		description: 'Pista de carreras con coches y obstáculos',
		price: 69.99,
		images: [
			{
				id: 'img-t11-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Pista de Carreras',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.6, count: 80 },
	},
	{
		id: 'prod-t12',
		name: 'Juego de Construcción de Madera',
		description: 'Set de bloques de madera para construir estructuras',
		price: 54.99,
		images: [
			{
				id: 'img-t12-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Juego de Construcción de Madera',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.9, count: 105 },
	},
	{
		id: 'prod-t13',
		name: 'Set de Cocina Infantil',
		description: 'Cocina de juguete con accesorios y sonidos',
		price: 79.99,
		images: [
			{
				id: 'img-t13-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Cocina Infantil',
				isMain: true,
			},
		],
		stock: 20,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.7, count: 90 },
	},
	{
		id: 'prod-t14',
		name: 'Juego de Memoria',
		description: 'Juego de memoria con tarjetas ilustradas',
		price: 19.99,
		images: [
			{
				id: 'img-t14-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Juego de Memoria',
				isMain: true,
			},
		],
		stock: 60,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.8, count: 120 },
	},
	{
		id: 'prod-t15',
		name: 'Set de Instrumentos Musicales',
		description: 'Kit de instrumentos musicales para niños',
		price: 44.99,
		images: [
			{
				id: 'img-t15-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Instrumentos Musicales',
				isMain: true,
			},
		],
		stock: 30,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.6, count: 85 },
	},
	{
		id: 'prod-t16',
		name: 'Juego de Rol',
		description: 'Juego de rol con personajes y escenarios',
		price: 49.99,
		images: [
			{
				id: 'img-t16-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Juego de Rol',
				isMain: true,
			},
		],
		stock: 25,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.7, count: 70 },
	},
	{
		id: 'prod-t17',
		name: 'Set de Construcción de Vehículos',
		description:
			'Kit para construir diferentes vehículos con piezas intercambiables',
		price: 39.99,
		images: [
			{
				id: 'img-t17-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Construcción de Vehículos',
				isMain: true,
			},
		],
		stock: 40,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.8, count: 95 },
	},
	{
		id: 'prod-t18',
		name: 'Juego de Mesa Estratégico',
		description: 'Juego de estrategia para 2-4 jugadores',
		price: 34.99,
		images: [
			{
				id: 'img-t18-1',
				url: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Juego de Mesa Estratégico',
				isMain: true,
			},
		],
		stock: 35,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.9, count: 110 },
	},
	{
		id: 'prod-t19',
		name: 'Set de Manualidades',
		description: 'Kit de manualidades con materiales y guía de proyectos',
		price: 29.99,
		images: [
			{
				id: 'img-t19-1',
				url: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Set de Manualidades',
				isMain: true,
			},
		],
		stock: 45,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.7, count: 85 },
	},
	{
		id: 'prod-t20',
		name: 'Juego de Construcción de Ciudad',
		description:
			'Set para construir una ciudad completa con edificios y vehículos',
		price: 89.99,
		images: [
			{
				id: 'img-t20-1',
				url: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
				alt: 'Juego de Construcción de Ciudad',
				isMain: true,
			},
		],
		stock: 20,
		categoryId: 'cat-8',
		category: categories[7],
		rating: { rate: 4.8, count: 75 },
	},
];

export const products: Product[] = [
	...electronicos,
	...ropa,
	...hogar,
	...joyeria,
	...deportes,
	...libros,
	...belleza,
	...juguetes,
];
